# Generated by Django 5.0.1 on 2024-01-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagenew', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='new',
            name='date_of_create',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Дата создания новости'),
        ),
    ]
